# Generated by Django 4.2.6 on 2024-10-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0002_case_party_remove_client_id_client_case_no_ruling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='other_parties',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='other_partiesreps',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
