# Generated by Django 4.2.6 on 2024-10-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0003_client_other_parties_client_other_partiesreps'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='matter_coming_up',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='File_no',
            field=models.CharField(default='BMD000', max_length=10),
        ),
    ]
