# Generated by Django 4.2.6 on 2024-10-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0004_case_matter_coming_up_client_file_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='Advocate_assigned',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
