# Generated by Django 3.2.24 on 2024-11-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0005_case_advocate_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(default='uploads/profile/profile.jpg', upload_to='uploads/profile')),
            ],
        ),
    ]
