# Generated by Django 3.2.24 on 2024-11-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=254),
        ),
    ]
