# Generated by Django 3.2.24 on 2024-11-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0007_userprofile_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userprofile',
            new_name='user_profile',
        ),
    ]
